services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anaki_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/html
    networks:
      - anaki_network
    user: www-data
    
  nginx:
    image: nginx:alpine
    container_name: anaki_nginx
    restart: unless-stopped
    ports:
      - "4080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - anaki_network

networks:
  anaki_network:
    external: true

volumes:
  dbdata:
    driver: local
