<?php

namespace App\Constants;

class NotificationConst
{
    const SIDE_NAV = "SIDE_NAV";
    const LOGIN = "LOGGED_IN";
    const BALANCE_UPDATE = "BALANCE_UPDATE";
    const BALANCE_ADDED = "BALANCE_ADDED";
    const TRADE_CREATED = "TRADE_CREATED";
    const COUNTER_OFFER = "COUNTER_OFFER";
    const OFFER = "OFFER";
    const TRANSACTION_CREATED = "TRANSACTION_CREATED";
    const EXCROW_TRANSACTION_ADDED = "EXCROW_TRANSACTION_ADDED";
    const MARKETPLACE_TRANSACTION_ADDED = "MARKETPLACE_TRANSACTION_ADDED";
    const MONEY_OUT = "MONEY_OUT";

    const TRADE_CANCELLED = "TRADE_CANCELLED";
    const TRADE_PAYMENT_COMPLETED = "TRADE_PAYMENT_COMPLETED";
    const TRADE_COMPLETED = "TRADE_COMPLETED";
    const TRADE_STARTED = "TRADE_STARTED";
    const TRADE_FUNDS_DEPOSITED = "TRADE_FUNDS_DEPOSITED";
    const TRADE_AUTO_EXPIRED = "TRADE_AUTO_EXPIRED";
    const DISPUTE_STARTED = "DISPUTE_STARTED";
    const DISPUTE_RESOLVED = "DISPUTE_RESOLVED";
    const USDT_DEPOSIT_COMPLETED = "USDT_DEPOSIT_COMPLETED";
    const USDT_RECEIVING = "USDT_RECEIVING";
    const USDT_SENDING = "USDT_SENDING";
    const USDT_RECEIVED = "USDT_RECEIVED";
    const USDT_SENT = "USDT_SENT";
    const ATTACHMENT_UPLOADED = "ATTACHMENT_UPLOADED";
    const PROOF_SENT = "PROOF_SENT";
    const PROOF_RECEIVE = "PROOF_RECEIVE";
}
